create table public."Purchases" (
                                    id bigint generated by default as identity not null,
                                    created_at timestamp with time zone not null default now(),
                                    stripe_payment_id character varying not null,
                                    payment_authorised_timestamp timestamp with time zone null,
                                    payment_method character varying null,
                                    payment_amount_pence smallint not null,
                                    items json not null,
                                    user_id bigint not null,
                                    payment_confirmed boolean not null default false,
                                    coupon_code character varying null,
                                    t character varying null,
                                    constraint Purchases_pkey primary key (id),
                                    constraint Purchases_stripe_payment_id_key unique (stripe_payment_id),
                                    constraint Purchases_user_id_fkey foreign KEY (user_id) references "Users" (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;