create table public."Users" (
                                id bigint generated by default as identity not null,
                                created_at timestamp with time zone not null default now(),
                                first_name character varying null,
                                surname character varying null,
                                email character varying not null,
                                stripe_customer_id character varying null,
                                kajabi_customer_id character varying null,
                                eb_subscriber_id character varying null,
                                kit_subscriber_id character varying null,
                                subscribed_to_marketing boolean null default false,
                                constraint Users_pkey primary key (id),
                                constraint Users_email_key unique (email)
) TABLESPACE pg_default;