create table public."WebinarEmailsSent"
(
    id                  bigint generated by default as identity not null,
    created_at          timestamp with time zone                not null default now(),
    webinar_id          bigint                                  not null,
    email_template_name character varying                       not null,
    constraint WebinarEmailsSent_pkey primary key (id),
    constraint WebinarEmailsSent_webinar_id_fkey foreign KEY (webinar_id) references "Webinars" (webinar_id)
) TABLESPACE pg_default;