create table public."WebinarTickets"
(
    id                                  bigint generated by default as identity not null,
    created_at                          timestamp with time zone                not null default now(),
    webinar_id                          bigint                                  not null,
    ticket_id                           bigint                                  not null,
    ticket_name                         character varying                       not null,
    user_id                             bigint                                  not null,
    is_recording_ticket                 boolean                                 not null,
    email_sent_sent_starting_in_2_hours boolean                                 not null,
    email_sent_sent_starting_in_20_mins boolean                                 not null,
    email_sent_recording                boolean                                 not null,
    purchase_id                         bigint                                  not null,
    constraint WebinarTickets_pkey primary key (id),
    constraint WebinarTickets_purchase_id_fkey foreign KEY (purchase_id) references "Purchases" (id),
    constraint WebinarTickets_user_id_fkey foreign KEY (user_id) references "Users" (id),
    constraint WebinarTickets_webinar_id_fkey foreign KEY (webinar_id) references "Webinars" (webinar_id)
) TABLESPACE pg_default;